name: Deploy Shiny Python App to Posit Connect

on:
  push:
    branches: [main]
    paths:
      - '05_hackathon/congestion_tracker/dashboard/**'
      - '.github/workflows/deploy-shinypy.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14.2'

      - name: Publish to Posit Connect
        uses: rstudio/actions/connect-publish@main
        with:
          url: ${{ secrets.CONNECT_SERVER }}
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: acl
          dir: 05_hackathon/congestion_tracker/dashboard
          force: false
          manifest: manifestme.sh
          manifest-path: dashboard/manifestme.sh
          manifest-args: --app-mode python-shiny --entrypoint app
          manifest-args: --app-mode python-shiny --entrypoint app